#!/usr/bin/env bash

minecraft_versions=(
    "https://launcher.mojang.com/v1/objects/0c8689f904922af71c7144dcfb81bce976cadd49/client.jar" # 1.7.2 
    "https://launcher.mojang.com/v1/objects/e80d9b3bf5085002218d4be59e668bac718abbc6/client.jar" # 1.7.10
    "https://launcher.mojang.com/v1/objects/d722504db9de2b47f46cc592b8528446272ae648/client.jar" # 1.8.0
    "https://launcher.mojang.com/v1/objects/0983f08be6a4e624f5d85689d1aca869ed99c738/client.jar" # 1.8.8
    "https://launcher.mojang.com/v1/objects/3870888a6c3d349d3771a3e9d16c9bf5e076b908/client.jar" # 1.8.9
    "https://launcher.mojang.com/v1/objects/2f67dfe8953299440d1902f9124f0f2c3a2c940f/client.jar" # 1.9.0
    "https://launcher.mojang.com/v1/objects/19106fd5e222dca0f2dde9f66db8384c9a7db957/client.jar" # 1.9.2
    "https://launcher.mojang.com/v1/objects/4a61c873be90bb1196d68dac7b29870408c56969/client.jar" # 1.9.4
    "https://launcher.mojang.com/v1/objects/ba038efbc6d9e4a046927a7658413d0276895739/client.jar" # 1.10.0
    "https://launcher.mojang.com/v1/objects/dc8e75ac7274ff6af462b0dcec43c307de668e40/client.jar" # 1.10.2
    "https://launcher.mojang.com/v1/objects/780e46b3a96091a7f42c028c615af45974629072/client.jar" # 1.11.0
    "https://launcher.mojang.com/v1/objects/db5aa600f0b0bf508aaf579509b345c4e34087be/client.jar" # 1.11.2
    "https://launcher.mojang.com/v1/objects/909823f9c467f9934687f136bc95a667a0d19d7f/client.jar" # 1.12.0
    "https://launcher.mojang.com/v1/objects/83385d346cf7f97d1e447b888750fb88e9928b93/client.jar" # 1.12.1
    "https://launcher.mojang.com/v1/objects/0f275bc1547d01fa5f56ba34bdc87d981ee12daf/client.jar" # 1.12.2
    "https://launcher.mojang.com/v1/objects/c0b970952cdd279912da384cdbfc0c26e6c6090b/client.jar" # 1.13.0
    "https://launcher.mojang.com/v1/objects/8de235e5ec3a7fce168056ea395d21cbdec18d7c/client.jar" # 1.13.1
    "https://launcher.mojang.com/v1/objects/30bfe37a8db404db11c7edf02cb5165817afb4d9/client.jar" # 1.13.2
    "https://launcher.mojang.com/v1/objects/ca6c5a139045967229975c0c0b7f93e78b4314c2/client.jar" # 1.14.2
    "https://launcher.mojang.com/v1/objects/af100b34ec7ef2b8b9cf7775b544d21d690dddec/client.jar" # 1.14.3
    "https://launcher.mojang.com/v1/objects/8c325a0c5bd674dd747d6ebaa4c791fd363ad8a9/client.jar" # 1.14.4
    "https://launcher.mojang.com/v1/objects/e3f78cd16f9eb9a52307ed96ebec64241cc5b32d/client.jar" # 1.15.2
    "https://launcher.mojang.com/v1/objects/c9abbe8ee4fa490751ca70635340b7cf00db83ff/client.jar" # 1.16.1
    "https://launcher.mojang.com/v1/objects/653e97a2d1d76f87653f02242d243cdee48a5144/client.jar" # 1.16.2
    "https://launcher.mojang.com/v1/objects/1321521b2caf934f7fc9665aab7e059a7b2bfcdf/client.jar" # 1.16.3
    "https://launcher.mojang.com/v1/objects/1952d94a0784e7abda230aae6a1e8fc0522dba99/client.jar" # 1.16.4
    "https://launcher.mojang.com/v1/objects/37fd3c903861eeff3bc24b71eed48f828b5269c8/client.jar" # 1.16.5
    "https://launcher.mojang.com/v1/objects/1cf89c77ed5e72401b869f66410934804f3d6f52/client.jar" # 1.17.0
    "https://launcher.mojang.com/v1/objects/8d9b65467c7913fcf6f5b2e729d44a1e00fde150/client.jar" # 1.17.1
    "https://launcher.mojang.com/v1/objects/d49eb6caed53d23927648c97451503442f9e26fd/client.jar" # 1.18.0
    "https://launcher.mojang.com/v1/objects/7e46fb47609401970e2818989fa584fd467cd036/client.jar" # 1.18.1
    "https://launcher.mojang.com/v1/objects/2e9a3e3107cca00d6bc9c97bf7d149cae163ef21/client.jar" # 1.18.2
)

optifine_jars=(
    "https://optifine.net/downloadx?f=OptiFine_1.7.2_HD_U_F7.jar&x=609b41701cd0c45708c03c89761ec0a6"
    "https://optifine.net/downloadx?f=OptiFine_1.7.10_HD_U_E7.jar&x=609b41701cd0c45708c03c89761ec0a6"
    "https://optifine.net/downloadx?f=OptiFine_1.8.0_HD_U_I7.jar&x=609b41701cd0c45708c03c89761ec0a6"
    "https://optifine.net/downloadx?f=OptiFine_1.8.8_HD_U_I7.jar&x=609b41701cd0c45708c03c89761ec0a6"
    "https://optifine.net/downloadx?f=OptiFine_1.8.9_HD_U_M5.jar&x=cd435cc07ab10eb7d0196ef35fb3898e"
    "https://optifine.net/downloadx?f=OptiFine_1.9.0_HD_U_I5.jar&x=cd435cc07ab10eb7d0196ef35fb3898e"
    "https://optifine.net/downloadx?f=OptiFine_1.9.2_HD_U_E3.jar&x=cd435cc07ab10eb7d0196ef35fb3898e"
    "https://optifine.net/downloadx?f=OptiFine_1.9.4_HD_U_I5.jar&x=1ba554e9eddb20876a290f68c06c0143"
    "https://optifine.net/downloadx?f=OptiFine_1.10_HD_U_I5.jar&x=1ba554e9eddb20876a290f68c06c0143"
    "https://optifine.net/downloadx?f=OptiFine_1.10.2_HD_U_I5.jar&x=1ba554e9eddb20876a290f68c06c0143"

)

minecraft_jsons=(
    "https://launchermeta.mojang.com/v1/packages/83a7d28760ed623225e7cb2e29db140cc68540e8/1.7.2.json"
    "https://launchermeta.mojang.com/v1/packages/2e818dc89e364c7efcfa54bec7e873c5f00b3840/1.7.10.json"
    "https://launchermeta.mojang.com/v1/packages/c6309181ce8df8a06ed556e315cd4636c4082b9a/1.8.json"
    "https://launchermeta.mojang.com/v1/packages/389ee2576f1c7ac6efe0edcec79f2e465d2a5278/1.8.8.json"
    "https://launchermeta.mojang.com/v1/packages/856d9bec08b0d567de39f46efaf4b76066b53059/1.8.9.json"
    "https://launchermeta.mojang.com/v1/packages/fab85b386a3de3009e5944b0183ce063faa09691/1.9.json"
    "https://launchermeta.mojang.com/v1/packages/3cc8cee91366290508c8767e8826c6352c2b89c5/1.9.2.json"
    "https://launchermeta.mojang.com/v1/packages/7f40b382dedcfe9eca74a5b14d615075ec34c108/1.9.4.json"
    "https://launchermeta.mojang.com/v1/packages/0590cc1c11f1be246af9d972f919693bf6b0d1f6/1.10.json"
    "https://launchermeta.mojang.com/v1/packages/9e23991d61e9b4eb9dfee56cb8ee7392fb925aff/1.10.2.json"
    "https://launchermeta.mojang.com/v1/packages/340d2e0f200af20b1e4d5da501facc7fc1cfb0e5/1.11.json"
    "https://launchermeta.mojang.com/v1/packages/6bd228727ed48bd7ac7bdc0088587dad0fb7c02b/1.11.2.json"
    "https://launchermeta.mojang.com/v1/packages/367843437acbae63de3084dd6afd3dd8bd2a7479/1.12.json"
    "https://launchermeta.mojang.com/v1/packages/24b28f562e354309697a1c9d835dea55a185df1e/1.12.1.json"
    "https://launchermeta.mojang.com/v1/packages/6e69e85d0f85f4f4b9e12dd99d102092a6e15918/1.12.2.json"
    "https://launchermeta.mojang.com/v1/packages/1efd5dfcae060b847706500e408a76674922de89/1.13.json"
    "https://launchermeta.mojang.com/v1/packages/bbed6214da465e25f769366835b7321d5380a1fa/1.13.1.json"
    "https://launchermeta.mojang.com/v1/packages/081135896bfc24424033c1ec0b2e5d3c69c5f764/1.13.2.json"
    "https://launchermeta.mojang.com/v1/packages/8b96abed06b23d3b752e653ada36062d70bf3da1/1.14.2.json"
    "https://launchermeta.mojang.com/v1/packages/2b9823a8699fb6811acd1f553c5bee009d30f64e/1.14.3.json"
    "https://launchermeta.mojang.com/v1/packages/fbe94183241ba2fcf8cfb71703d9a145c225a76e/1.14.4.json"
    "https://launchermeta.mojang.com/v1/packages/b57e2563648f1a657dddab12d5626b0e6dde6ffd/1.15.2.json"
    "https://launchermeta.mojang.com/v1/packages/007e584150d3eb937762a491c340732d01cce945/1.16.1.json"
    "https://launchermeta.mojang.com/v1/packages/363cf3fef00f554a93ff3c54b189465efeb3d0bb/1.16.2.json"
    "https://launchermeta.mojang.com/v1/packages/0b83240b80de22bdd47d93d2a0ed6f45bbd2779f/1.16.3.json"
    "https://launchermeta.mojang.com/v1/packages/e54eda49b4a3b6dc407b952e494d0c32da422693/1.16.4.json"
    "https://launchermeta.mojang.com/v1/packages/436877ffaef948954053e1a78a366b8b7c204a91/1.16.5.json"
    "https://launchermeta.mojang.com/v1/packages/44fa141917df947ed5a138f5cfe667a34f7bbaca/1.17.json"
    "https://launchermeta.mojang.com/v1/packages/8b976413591b4132fc4f27370dcd87ce1e50fb2f/1.17.1.json"
    "https://launchermeta.mojang.com/v1/packages/cdd1c0f485c0ea5a5aae60d4e62d316b2141f227/1.18.json"
    "https://launchermeta.mojang.com/v1/packages/b0bdc637e4c4cbf0501500cbaad5a757b04848ed/1.18.1.json"
    "https://launchermeta.mojang.com/v1/packages/86f9645f8398ec902cd17769058851e6fead68cf/1.18.2.json"
)

mcversion_folder="$HOME/.minecraft/versions"

download () {
    mkdir "${mcversion_folder}/$4"

    curl --request GET -sL \
        --output "${mcversion_folder}/$4/$4.jar" \
        --url "$1"

    curl --request GET -sL \
        --output "${mcversion_folder}/$4/$4.json" \
        --url "$2"

    curl --request GET -sL \
        --output "$(pwd)/$4.json" \
        --url "$3"

    java -cp "$(pwd)/$4.json" optifine.Patcher "${mcversion_folder}/$4/$4.jar" "$(pwd)/$4.json" "$(pwd)/Optifine_$4_MOD.jar"
    rm "${mcversion_folder}/$4/$4.jar" && rm "${mcversion_folder}/$4/$4.json"
}

main () {
    if [[ "$1" == "1.7.2" ]]; then
        download "${minecraft_versions[0]}" "${minecraft_jsons[0]}" "${optifine_jars[0]}" "1.7.2"

    elif [[ "$1" == "1.7.10" ]]; then
        download "${minecraft_versions[1]}" "${minecraft_jsons[1]}" "${optifine_jars[1]}" "1.7.10"

    elif [[ "$1" == "1.8" ]] || [[ "$1" == "1.8.0" ]]; then
        download "${minecraft_versions[2]}" "${minecraft_jsons[2]}" "${optifine_jars[2]}" "1.8"

    elif [[ "$1" == "1.8.8" ]]; then
        download "${minecraft_versions[3]}" "${minecraft_jsons[3]}" "${optifine_jars[3]}" "1.8.8"

    elif [[ "$1" == "1.8.9" ]]; then
        download "${minecraft_versions[4]}" "${minecraft_jsons[4]}" "${optifine_jars[4]}" "1.8.9"

    elif [[ "$1" == "1.9" ]] || [[ "$1" == "1.9.0" ]]; then
        download "${minecraft_versions[5]}" "${minecraft_jsons[5]}" "${optifine_jars[5]}" "1.9"

    elif [[ "$1" == "1.9.2" ]]; then
        download "${minecraft_versions[6]}" "${minecraft_jsons[6]}" "${optifine_jars[6]}" "1.9.2"

    elif [[ "$1" == "1.9.4" ]]; then
        download "${minecraft_versions[7]}" "${minecraft_jsons[7]}" "${optifine_jars[7]}" "1.9.4"

    elif [[ "$1" == "1.10" ]] || [[ "$1" == "1.10.0" ]]; then
        download "${minecraft_versions[8]}" "${minecraft_jsons[8]}" "${optifine_jars[8]}" "1.10"

    elif [[ "$1" == "1.10.1" ]]; then
        download "${minecraft_versions[9]}" "${minecraft_jsons[9]}" "${optifine_jars[9]}" "1.10.1"

    elif [[ "$1" == "1.10.2" ]]; then
        download "${minecraft_versions[10]}" "${minecraft_jsons[10]}" "${optifine_jars[10]}" "1.10.2"

    elif [[ "$1" == "1.11" ]] || [[ "$1" == "1.11.0" ]]; then
        download "${minecraft_versions[11]}" "${minecraft_jsons[11]}" "${optifine_jars[11]}" "1.11"

    elif [[ "$1" == "1.11.2" ]]; then
        download "${minecraft_versions[12]}" "${minecraft_jsons[12]}" "${optifine_jars[12]}" "1.11.2"

    elif [[ "$1" == "1.12" ]] || [[ "$1" == "1.12.0" ]]; then
        download "${minecraft_versions[13]}" "${minecraft_jsons[13]}" "${optifine_jars[13]}" "1.12"

    elif [[ "$1" == "1.12.1" ]]; then
        download "${minecraft_versions[14]}" "${minecraft_jsons[14]}" "${optifine_jars[14]}" "1.12.1"

    elif [[ "$1" == "1.12.2" ]]; then
        download "${minecraft_versions[15]}" "${minecraft_jsons[15]}" "${optifine_jars[15]}" "1.12.2"

    elif [[ "$1" == "1.13" ]] || [[ "$1" == "1.13.0" ]]; then
        download "${minecraft_versions[16]}" "${minecraft_jsons[16]}" "${optifine_jars[16]}" "1.13"

    elif [[ "$1" == "1.13.1" ]]; then
        download "${minecraft_versions[17]}" "${minecraft_jsons[17]}" "${optifine_jars[17]}" "1.13.1"

    elif [[ "$1" == "1.13.2" ]]; then
        download "${minecraft_versions[18]}" "${minecraft_jsons[18]}" "${optifine_jars[18]}" "1.13.2"

    elif [[ "$1" == "1.14.2" ]]; then
        download "${minecraft_versions[19]}" "${minecraft_jsons[19]}" "${optifine_jars[19]}" "1.14.2"

    elif [[ "$1" == "1.14.3" ]]; then
        download "${minecraft_versions[20]}" "${minecraft_jsons[20]}" "${optifine_jars[20]}" "1.14.3"

    elif [[ "$1" == "1.14.4" ]]; then
        download "${minecraft_versions[21]}" "${minecraft_jsons[21]}" "${optifine_jars[21]}" "1.14.4"

    elif [[ "$1" == "1.15.2" ]]; then
        download "${minecraft_versions[22]}" "${minecraft_jsons[22]}" "${optifine_jars[22]}" "1.15.2"

    elif [[ "$1" == "1.16.1" ]]; then
        download "${minecraft_versions[23]}" "${minecraft_jsons[23]}" "${optifine_jars[23]}" "1.16.1"

    elif [[ "$1" == "1.16.2" ]]; then
        download "${minecraft_versions[24]}" "${minecraft_jsons[24]}" "${optifine_jars[24]}" "1.16.2"

    elif [[ "$1" == "1.16.3" ]]; then
        download "${minecraft_versions[25]}" "${minecraft_jsons[25]}" "${optifine_jars[25]}" "1.16.3"

    elif [[ "$1" == "1.16.4" ]]; then
        download "${minecraft_versions[26]}" "${minecraft_jsons[26]}" "${optifine_jars[26]}" "1.16.4"

    elif [[ "$1" == "1.16.5" ]]; then
        download "${minecraft_versions[27]}" "${minecraft_jsons[27]}" "${optifine_jars[27]}" "1.16.5"

    elif [[ "$1" == "1.17" ]] || [[ "$1" == "1.17.0" ]]; then
        download "${minecraft_versions[28]}" "${minecraft_jsons[28]}" "${optifine_jars[28]}" "1.17"

    elif [[ "$1" == "1.17.1" ]]; then
        download "${minecraft_versions[29]}" "${minecraft_jsons[29]}" "${optifine_jars[29]}" "1.17.1"

    elif [[ "$1" == "1.18" ]] || [[ "$1" == "1.18.0" ]]; then
        download "${minecraft_versions[30]}" "${minecraft_jsons[30]}" "${optifine_jars[30]}" "1.18"

    elif [[ "$1" == "1.18.1" ]]; then
        download "${minecraft_versions[31]}" "${minecraft_jsons[31]}" "${optifine_jars[31]}" "1.18.1"

    elif [[ "$1" == "1.18.2" ]]; then
        download "${minecraft_versions[32]}" "${minecraft_jsons[32]}" "${optifine_jars[32]}" "1.18.2"

    else
        printf "[ERROR] Please choose a Minecraft version!\n"
    fi
    return 0
}

main "$1"